Add print of numbers to the left of the diff
gaspar-kolumban/diff64 pull request #1
Opened 2019-05-12 20:01 UTC by thommyj

Add input numbers to the left of the binary string. Also add an readme with example

2019-05-20 18:59 UTC, gaspar-kolumban commented on diff64.c
> +static uint32_t get_max_number_length(const uint64_t left_number, const uint64_t right_number)
Add this to the declaration section

2019-05-20 19:26 UTC, gaspar-kolumban requested changes

2019-05-20 19:26 UTC, gaspar-kolumban commented on diff64.c
> +    char number_length[max_string_length];
No VLA's please. Move the value of max_string_length inside the brackets and use "u" for the digits.

2019-05-20 19:26 UTC, gaspar-kolumban commented on diff64.c
> +    max_number_length =  get_max_number_length(left_number, right_number);
Add this line to the declaration of max_number_length and make it const (also there is two spaces before the function call :P)

2019-05-20 19:26 UTC, gaspar-kolumban commented on diff64.c
> +    printf("0x%0*lX ", max_number_length, left_number);
I prefer lower case "x".

2019-05-20 19:26 UTC, gaspar-kolumban commented on diff64.c
> +    printf("0x%0*lX ", max_number_length, right_number);
I prefer lower case "x".

2019-05-20 19:26 UTC, gaspar-kolumban commented on diff64.c
> +        max_number_length = right_number_length;
Should be left_number_length for the else branch.

2019-05-20 19:26 UTC, gaspar-kolumban commented on diff64.c
> +    snprintf(number_length, max_string_length, "%lX", left_number);
I prefer lower case "x", not that it really matters here but for the sake of consistency, if nothing else =)

2019-05-20 19:26 UTC, gaspar-kolumban commented on diff64.c
> +    snprintf(number_length, max_string_length, "%lX", right_number);
I prefer lower case "x", not that it really matters here but for the sake of consistency, if nothing else =)

2020-07-03 22:10 UTC, closed without merging

2020-07-03 22:13 UTC, thommyj commented
fixing in another pull request